### PR TITLE
Add static library target for msbuild

### PR DESCRIPTION
**Pull request by flandr**

### CODE REVIEW

**Comment by Cyan4973** [comment]
Completely forgot this PR :-1: 

No reason to block that, except that it's targeted at master, which is not consistent with branch policy.
Would you mind targeting your PR at "dev" branch instead ?

Alternatively, I can do it manually.

**Comment by psteinb** [comment]
hi yann,

no problem, I'll do that.

best,
peter

**Comment by psteinb** [comment]
hi to all,
I believe I mis-contributed to this PR! I submitted a similar PR here:
https://github.com/Cyan4973/lz4/pull/172
There I only alter the cmake build and do not add a seperate directory for visual studio etc. But as I stated in the PR, this results in static liblz4 builds on windows only (something to discuss).
Best,
P

**Comment by flandr** [comment]
> No reason to block that, except that it's targeted at master, which is not consistent with branch policy.
Would you mind targeting your PR at "dev" branch instead ?

Sorry, didn't notice this. Will do

**Comment by flandr** [comment]
Abandoned in favor of #173

**Pull request closed without merging**
