### PR TITLE
lz4cli: print library version along with cli version

### PR DESCRIPTION
**Pull request by jzhuge**
Resolve issue #192.

### CODE REVIEW

**Comment by Cyan4973** [comment]
As a minor detail,
one thing I would like to preserve is a welcomed message using < 80 characters,
to print on a single line.

One way to do so could be to remove the compilation date, and use the space for the library version.
It would also make lz4 cli build reproducible, which is slowly becoming a desirable property.

**Comment by t-mat** [comment]
Hi @jzhuge,  It's good PR :)  I found there are 2 minor issues:

- Since this PR is also useful to check actual dynamic linked libraries version, `LZ4_versionNumber()` would be better than `LZ4_VERSION_NUMBER`.
- We should consider once about multiple dot version number such as `1.7.3`.

**Comment by jzhuge** [comment]
Great comments. I will make changes.

**Comment by Cyan4973** [comment]
Ah, and now that I noticed,
no PR to master please.
They must go first through "dev" branch (or their own feature branch when available).

**Pull request closed without merging**
