### PR TITLE
Modified lz4frame enum, by @t-mat

### PR DESCRIPTION
**Pull request by Cyan4973**

### CODE REVIEW

**Comment by Cyan4973** [comment]
I'm wondering if using macro for old enum is good enough.
This question looks useful mostly in the context of DLL.

**Comment by t-mat** [comment]
Here is experimental implementation which eliminate macro constants :

 - https://github.com/t-mat/lz4/blob/issue/90-exp/lib/lz4frame.h#L65

Perhaps, this notation is better for deprecation attributes.

**Comment by Cyan4973** [comment]
Looks clean :)

**Comment by Cyan4973** [comment]
Do you intend to make it a pull request ?

**Comment by t-mat** [comment]
Yes. I'll send PR.

**Pull request merged**
