### PR TITLE
Added debianization

### PR DESCRIPTION
**Pull request by bioothod**
Currently all debian distros ship rather old and incomplete subset of lz4, in particular they all miss frame processing implementation.
I'm not sure whether new package will ever find its way into debian distros, but having all debianizations in the source is quite handy for those who may wish to build it locally.

Debianization is rather simple (there are lintian bugs and warnings for instance). Tested on wheezy.

### CODE REVIEW

**Comment by Cyan4973** [comment]
Thanks, looks like a good commit request.

Note that no commit is ever pulled directly into master. New commits must either land first into their own feature branch, or into dev branch.

**Comment by bioothod** [comment]
Ok, I see. I didn't know about branch naming policy, so created PR against master.
Should I remake pull request or you will merge it by hands?
I only updated CMakeFiles.txt outside of the debian tree, so there should be no merge conflicts.

**Comment by Cyan4973** [comment]
> Should I remake pull request or you will merge it by hands?

As you wish

**Comment by bioothod** [comment]
I've added https://github.com/Cyan4973/lz4/pull/142 against `dev` branch, is it ok?

**Comment by Cyan4973** [comment]
yep. replaced by #142

**Pull request closed without merging**
